### PR TITLE
force-downcast `updateUIObjC` handler's value to avoid silent failure.

### LINKED ISSUE #34: Obj-C Interop: `updateUI` block not called when value is `nil`
In the objc interop code for ServiceTasks, [there is a type-check](https://github.com/Electrode-iOS/ELWebService/blob/master/Source/Core/ServiceTask%2BObjC.swift#L135) before the `updateUI` block is called:

```
if let value = value as? AnyObject {
    handler(value)
}
```

If `value` is `nil`, the check fails and the block is not called. I think it should be `value as? AnyObject?`.

### PR DESCRIPTION
**Pull request by angelodipaolo**
Fixes #34.

### CODE REVIEW

File: Source/Core/ServiceTask+ObjC.swift [hunk 1]
```diff
@@ -132,9 +132,7 @@ extension ServiceTask {
     */
     @objc public func updateUIObjC(handler: (AnyObject?) -> Void) -> Self {
         return updateUI { value in
-            if let value = value as? AnyObject {
-                handler(value)
-            }
+            handler(value as! AnyObject?)
         }
```
Comment (bsneed) [inline Source/Core/ServiceTask+ObjC.swift]: would it not be better to add ....

```else {
    exceptionFailure("... some message ... ")
}```

instead?

Comment (angelodipaolo) [inline Source/Core/ServiceTask+ObjC.swift]: Originally I did have an else in there with a fatalError() but it seemed unnecessary since it's just raising the same error that the runtime would throw.

```
if let value = value as? AnyObject? {
    handler(value)
} else {
    fatalError("Failed to downcast Any? type to AnyObject?")
}
```

Comment (bsneed) [inline Source/Core/ServiceTask+ObjC.swift]: Ok.  I think i misunderstood the intent.  Thanks for clearing it up for me on slack.
